version: "3"

services:
  mc_sebi:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      FABRIC_LAUNCHER: "server/fabric-server-launch.jar"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data
